version: "3.9"  # optional since v1.27.0
services:
  backend:
    build: backend/
    ports:
      - "8080:80"
      - "8081:81"
  flapper:
    build: flapper/
    ports:
      - "9022:22"
      - "9080:80"
  haproxy:
    build: haproxy/
    ports:
      - "5022:22"
      - "5080:80"
      - "5443:443"
      - "5888:888"
  vector:
    build: vector/
    environment:
    - DATADOG_API_KEY=${DATADOG_API_KEY}
    ports:
      - "6514:514"
      - "6686:8686"
